.\" -*- nroff -*-
.\" Copyright 1993, 1994, 1995 by Theodore Ts'o.  All Rights Reserved.
.\" This file may be copied under the terms of the GNU Public License.
.\"
.TH FINDFS 8 "February 2009" "util-linux" "System Administration"
.SH NAME
findfs \- find a filesystem by label or UUID
.SH SYNOPSIS
.B findfs
.BI NAME= value
.SH DESCRIPTION
.B findfs
will search the block devices in the system looking for a filesystem or
partition with specified tag. The currently supported tags are:
.TP
.B LABEL=<label>
Specifies filesystem label.
.TP
.B UUID=<uuid>
Specifies filesystem UUID.
.TP
.B PARTUUID=<uuid>
Specifies partition UUID. This partition identifier is supported for example for
GUID  Partition  Table (GPT) partition tables.
.TP
.B PARTLABEL=<label>
Specifies partition label (name). The partition labels are supported for example for
GUID Partition Table (GPT) or MAC partition tables.
.PP
If the filesystem or partition is found, the device name will be printed on
stdout.

The complete overview about filesystems and partitions you can get for example
by
.RS

.br
.BI "lsblk \-\-fs"
.br

.BI "partx --show <disk>"
.br

.BI blkid
.br

.RE

.PP
.SH AUTHOR
.B findfs
was originally written by Theodore Ts'o (tytso@mit.edu) and re-written for
the util-linux package by Karel Zak (kzak@redhat.com).
.SH ENVIRONMENT
.IP LIBBLKID_DEBUG=0xffff
enables debug output.
.SH SEE ALSO
.BR blkid (8),
.BR lsblk (8),
.BR partx (8)
.SH AVAILABILITY
The findfs command is part of the util-linux package and is available from
ftp://ftp.kernel.org/pub/linux/utils/util-linux/.
